### ISSUE TITLE
while open press 4 then press 1.

### ISSUE THREAD

**Issue by xmh19936688** [googlesamples/android-BasicTransition#2]
the red one is small while start app. press 4 let the red one become bigger. then press 1 the red one will not trans-back.

**Comment by keyboardsurfer** [comment]
Internal: 26812497

**Comment by yaraki** [comment]
This is expected.
1 is a scene based on the live layout hierarchy, and 4 is a dynamic transition. Pressing 4 when 1 is selected will modify the scene,. Pressing 1 then still brings back the scene, but it is modified.
Scene 2 and 3 are statically generated from resources, and their scenes are not permanently modified even after a dynamic transition (pressing 4).
If you need to bring back the previous state, use approach 2 or 3.
